<?php
/** @var \SM\Promotion\Block\Widget\PromotionProduct $block */
$class = "promotion-product";
$type = "promotion-product";
$image = 'category_page_grid';
$buttonTitle = __('Add to Cart');
$title = $block->getData('title');
$enable_carousel = $block->getData('enable_carousel');
$number_of_product = $block->getData('number_of_product');
$promotion_products = $block->getPromotionProduct($number_of_product);
?>
<?php if($promotion_products) : ?>
    <div class="block <?= $block->escapeHtmlAttr($class) ?>">
        <div class="content-heading">
            <h2 class="title"><?= $block->escapeHtml($title) ?></h2>
        </div>
        <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
            <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                <ol class="products list items product-items ol-<?= $block->escapeHtmlAttr($type) ?>">
                    <?php foreach ($promotion_products as $_product) :?>
                        <li class="item product product-item">
                            <div class="product-item-info">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>" class="product photo product-item-photo">
                                    <?= $block->getImage($_product, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" title="<?= $block->escapeHtml($_product->getName()) ?>" href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>">
                                            <?php echo $block->escapeHtml($_product->getName()); ?>
                                            <?php echo $block->escapeHtml($_product->getId()); ?>
                                        </a>
                                    </strong>
                                    <?php echo $block->getProductPriceHtml($_product); ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".ol-promotion-product").slick({
                dots: false,
                infinite: true,
                speed: 300,
                autoplay: <?= $enable_carousel ?>,
                arrows:true,
                vertical: false,
                slidesToShow: 4,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 1120,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 1
                        }

                    },
                    {
                        breakpoint: 860,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 600,
                        settings: {
                            slidesToShow:1,
                            slidesToScroll: 1
                        }
                    }
                ],
            });
        });
    });
</script>
